<a href="https://colab.research.google.com/github/dwivedys/Python_Programs/blob/Numpy_Programs/Arbitrarily_sized_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
''' This function performs the following three tasks:
Given a numpy array of arbitrary size, 
1. It reshapes the array into desired shape
2. It then calculates row means
3. It also calculates column means
Finally it returns the re-shaped array and the row and column means '''

def generic_arr_calcs(n, s1, s2):
  import numpy as np
  arr = np.array([n]).reshape(s1, s2)
  column_means = arr.mean(axis = 0)
  row_means = arr.mean(axis = 1)
  return arr, column_means, row_means  

# **Example Usage**

In [5]:
import numpy as np
x = np.arange(20)
generic_arr_calcs(x, 4,5)

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([ 7.5,  8.5,  9.5, 10.5, 11.5]),
 array([ 2.,  7., 12., 17.]))