<a href="https://colab.research.google.com/github/dwivedys/Python_Numpy/blob/Numpy_Programs/LearningNumpyArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
CURVE_CENTER = 80
grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])
def curve(grades):
  average = grades.mean()
  change = CURVE_CENTER - average
  new_grades = grades + change
  return np.clip(new_grades, grades, 100)

In [2]:
curve(grades)

array([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

# **Below - we create an array which is a big list which comprises 4 separate arrays of 4 elements each**

In [33]:
table16 = np.array([[5,3,7,1], [2, 6, 7 ,9], [1, 1, 1, 1], [4, 3, 2, 0]])

# **Let us print the table16 to see how it looks**

In [34]:
table16


array([[5, 3, 7, 1],
       [2, 6, 7, 9],
       [1, 1, 1, 1],
       [4, 3, 2, 0]])

# **Max() function will return the max from the overall array**

In [35]:
table16.max()

9

# **Similar calculations can be performed to return max and min across axes; axis = 0 means column and axis = 1 means rows**

In [36]:
table16.max(axis = 0), table16.max(axis = 1), table16.min(axis = 0), table16.min(axis = 1)

(array([5, 6, 7, 9]),
 array([7, 9, 1, 4]),
 array([1, 1, 1, 0]),
 array([1, 2, 1, 0]))

**Now we will reshape the table16 in such a way that it has 2 big lists, each list having 4 smaller arrays of 2 elements each**

In [39]:
reshaped_table16 = table16.reshape(2,4,2)

**As can be seen - we now have a RESHAPED array which has 2 major arrays - (first argument), each of these two major arrays have 4 arrays - (second argument) of 2 elements each - (third and final argument) - reshape(2,4,2)**

In [41]:
reshaped_table16

array([[[5, 3],
        [7, 1],
        [2, 6],
        [7, 9]],

       [[1, 1],
        [1, 1],
        [4, 3],
        [2, 0]]])

In [50]:
reshaped_table16[0,1]

array([7, 1])

In [40]:
flattened_reshaped_table16 = reshaped_table16.flatten()
flattened_reshaped_table16

array([5, 3, 7, 1, 2, 6, 7, 9, 1, 1, 1, 1, 4, 3, 2, 0])

In [42]:
reshaped_table16[:,:,0]

array([[5, 7, 2, 7],
       [1, 1, 4, 2]])

In [43]:
reshaped_table16[1,:,0]

array([1, 1, 4, 2])

In [44]:
reshaped_table16[0,2,:]

array([2, 6])

In [18]:
reshaped_table16[0,1,:]

array([7, 1])

In [45]:
reshaped_table16[0,1,1]

1

In [46]:
table12 = np.array([[5,3,7,1], [2, 6, 7 ,9], [1, 1, 1, 1]])

In [51]:
table12.reshape(3,2,2) #3 overall arrays, with 2 arrays each having 2 elements each 

array([[[5, 3],
        [7, 1]],

       [[2, 6],
        [7, 9]],

       [[1, 1],
        [1, 1]]])

In [47]:
table12.reshape(2,3,2)

array([[[5, 3],
        [7, 1],
        [2, 6]],

       [[7, 9],
        [1, 1],
        [1, 1]]])