<a href="https://colab.research.google.com/github/dwivedys/Python_Programs/blob/Numpy_Programs/More_Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
np.array([1,2,3,4]).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [30]:
generic_arr_calcs([1,2,3,4], 2, 2)

(array([[1, 2],
        [3, 4]]), array([2., 3.]), array([1.5, 3.5]))

In [25]:
generic_arr_calcs(10, 5, 2)

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), array([4., 5.]), array([0.5, 2.5, 4.5, 6.5, 8.5]))

In [23]:
generic_arr_calcs(10, 2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
x = np.arange(10).reshape(5,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
x.mean(axis=1)

array([0.5, 2.5, 4.5, 6.5, 8.5])

In [9]:
fac([[1,2,3,4], [2, 3, 4, 5]])

array([[  1,   2,   6,  24],
       [  2,   6,  24, 120]])

In [15]:
print("A\tB\tC\t\t\tEnd")

A	B	C			End


In [17]:
x = 3.145323
print(f"{x:.03f}")

3.145


In [60]:
x = [1,2,3,4]
y = [5,6,7,8]
z = [9,10,11,12]
a = [13, 14, 15, 16]
b = [17,18,19,20]

arr = np.array([x,y,z,a,b])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [52]:
arr.shape

(5, 4)

In [53]:
arr_reshaped = arr.reshape(2,5,2)
arr_reshaped

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [78]:
arr_reshaped.ndim

3

In [54]:
arr_reshaped.shape

(2, 5, 2)

Give me the 1st sub-array from both sub-arrays

In [87]:
arr_reshaped[:,0,:]

array([[ 1,  2],
       [11, 12]])

Give me the 2nd sub-array from both sub-arrays

In [83]:
arr_reshaped[:,1,:]

array([[ 3,  4],
       [13, 14]])

Give me all the sub-arrays in the first sub-array

In [84]:
arr_reshaped[0,:,:]

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

Give me all the sub-arrays in the second sub-array

In [86]:
arr_reshaped[1,:,:]

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

Give me just the first element of each sub-array of both sub-arrays

In [85]:
arr_reshaped[:,:,0]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [56]:
arr_reshaped.mean(axis = 1)

array([[ 5.,  6.],
       [15., 16.]])

In [57]:
arr_reshaped.mean(axis = 0)

array([[ 6.,  7.],
       [ 8.,  9.],
       [10., 11.],
       [12., 13.],
       [14., 15.]])

x = [1,2,3,4]
y = [5,6,7,8]
z = [9,10,11,12]
a = [13, 14, 15, 16]
b = [17,18,19,20]



In [61]:
x1 = np.array([x, y])
x1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
x1.ndim

2

In [69]:
x1.mean(axis = 0)

array([3., 4., 5., 6.])

In [70]:
x1.mean(axis = 1)

array([2.5, 6.5])

In [72]:
x2 = np.array(x)

In [73]:
x2

array([1, 2, 3, 4])

In [74]:
x2.ndim

1

In [77]:
x2.mean()

2.5

AxisError: ignored