<a href="https://colab.research.google.com/github/dwivedys/Python_Programs/blob/Numpy_Programs/NumpyArraysContd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook - we will attempt to understand multi-dimensional numpy arrays.  

Before jumping into arrays of higher dimension it is worthwhile to understand scalar arrays

In [26]:
# A 0D Tensor or zero dimensional array - a scalar

x = np.array(1)
x

array(1)

It has 0 dimension

In [27]:
x.ndim

0

It has no shape - because it is a scalar

In [28]:
x.shape

()

# Now we move on to the exploration of multidimensional numpy arrays

As a motivating example - here's an example of a multi-dimensional numpy array
`numpy.array([[1,2], [3,4], [5,6])`. The way to read this array is as follows

You can see that there are a total of 3 sub-arrays within the big array. Each of the sub-array has 2 elements. This is what we refer to as a 2D numpy array or Tensor of Rank 2
You can run the shape command on this array and it will give the result `(3,2)` because the array has 3 sub-arrays, each sub-array having 2 elements

Please note that I will be using the terms numpy arrays and Tensors interchangeably. A multi-dimensional array and Tensors are the same technically speaking. We speak of dimensions when we talk of arrays - and we speak of Rank when we talk of Tensors

Note that a constant value like 1 or 2 or any constant number in the context of numpy arrays - declared like so - numpy.array(1) is an array with no dimensions or a zero dim Tensor (0D Tensor)


Now let's explore multi-dimensional numpy arrays

In [21]:
import numpy as np
motivating_example_array = np.array([[1,2], [3,4], [5,6]])
motivating_example_array.shape

(3, 2)

You can also run the **ndim** command to check the dimensions of the array, like so; Since this is a 2D array the answer will be 2

In [23]:
motivating_example_array.ndim

2

Now let us look at an example of a 3D numpy array or a Tensor of Rank 3;
As can be seen below, we now have a numpy array that has actually 2 sets of sub-arrays - the first set being `[[1,2], [3,4], [5,6]]` and the second set being `[[7,8], [9,10], [11,12]] `
Each of these "sets" have 3 sub-arrays each and 
Each sub-array has 2 elements 
Hence the SHAPE of this array will be `(2,3,2)`

In [22]:
a3Darray_example = np.array([[[1,2], [3,4], [5,6]], [[7,8], [9,10], [11,12]]])
a3Darray_example.shape

(2, 3, 2)

We can again run ndim to find out that it is indeed a 3D array

In [25]:
a3Darray_example.ndim

3

# Now I would like to explain multi-dimensional numpy arrays or Tensors in the context of the famous MNIST Dataset

In [1]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


**The train_images numpy array is a 3 Dimensional numpy array or a tensor of Rank 3; It has 60000 sub-arrays, with each sub-array itself having 28 sub-arrays and each of the 28 sub-arrays having 28 elements. 
We shall explore these points through the commands below**
  

In [2]:
train_images.shape

(60000, 28, 28)

In [19]:
train_images.ndim

3

**As stated above the very first element of train_images is an array which has 28 sub-arrays in it. So its length should be 28 as demonstrated below**

In [9]:
len(train_images[0])

28

**Again observe that the very first sub-array of the first element of train_images has 28 elements in it - so its length also will be 28**

In [8]:
len(train_images[0][0])

28

**Let us inspect the very first sub-array of train_images in the first of the 60000 sub-arrays**

In [10]:
train_images[0][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=uint8)

**And the second sub-array in the first group**

In [11]:
train_images[0][1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=uint8)

**And here's the first sub-array of the 59999th sub-array**

In [12]:
train_images[59999][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=uint8)

In [13]:
train_images[59999][0][0]

0

**Let us pull out the very last (28th) element of each of the sub-arrays; there should be a total of 60000 such elements broken into sub-arrays of 28 elements each**

In [15]:
train_images[:,:,27]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [17]:
len(train_images[:,:,27])

60000

In [18]:
len(train_images[:,:,27][0])

28

In [6]:
len(train_images[:,0:,])

60000

In [4]:
train_images[0:,:,]

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 